/**:
  # Global Parameters
  ros__parameters:
    tf_timeout_threshold: 0.05

/**:
  # Basic Robotics Functions
  # Platform
  platform:
    ros__parameters:
      enable_advanced_sensing: false  # Enable the possibility to access to all cameras and sensor
      publish_camera: false 

  # State Estimator
  state_estimator:
    ros__parameters:
      # Outdoor (GPS) Raw Odometry
      plugin_name: "raw_odometry"
      raw_odometry:
        use_gps: true  # Anchor tf tree at a GPS first measurement.

        # # Tf tree is anchored at manually set GPS coordinates.
        # gps_origin:
        #   set_origin: "manual"
        #   coordinates:
        #     latitude: 40.4168
        #     longitude: -3.7038
        #     altitude: 667.0

        # # Tf tree is anchored at GPS coordinates served by a service. The service must be called by the user.
        # gps_origin:
        #   set_origin: "service"

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: "takeoff_plugin_platform"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_platform"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_position"
      # go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_position"
      # follow_path_plugin_name: "follow_path_plugin_trajectory"

  # Trajectory Generation Behavior
  TrajectoryGeneratorBehavior:
    ros__parameters:
      plugin_name: "dynamic_mav_trajectory_generator"

# Specific Parameters for each drone
# drone0:
#   # Motion Capture
#   state_estimator:
#     ros__parameters:
#       rigid_body_name: "1"

